name: 'Bump GitOps repo'
inputs:
  service:
    required: true
  tag:
    required: true
  gitops-token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: vaishnavi639/yelb-gitops
        token: ${{ inputs.gitops-token }}
        path: gitops

    - shell: bash
      run: |
        cd gitops
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq
        yq -i '.${{ inputs.service }}.image.tag = "${{ inputs.tag }}"' helm/yelb/values.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add helm/yelb/values.yaml
        git commit -m "Update ${{ inputs.service }} image to ${{ inputs.tag }}"
        git push
